services:

  postgres_db:
    container_name: postgres_container
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U comsoftlab -d comsoftlab"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata:
