services:

  postgres_db:
    container_name: postgres_container
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U comsoftlab -d comsoftlab"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
      container_name: redis_container
      image: redis:latest
      restart: unless-stopped
      ports:
        - "6379:6379"

  web:
    container_name: django_container
    build: ./email_pj
    volumes:
      - media_files:/home/app/web/email_pj/media/email_files

    ports:
      - "7000:7000"
    env_file:
      - .env
    depends_on:
      - postgres_db
      - redis

volumes:
  pgdata:
  media_files:
