# Generated by Django 5.0.7 on 2024-07-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_uid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
